import React from 'react'
import Head from 'next/head'
import Header from '../../components/Header'
import Image from 'next/image'
import Footer from '../../components/Footer'
import styles from '../index.module.scss'
import { useEffect,useState } from 'react'
import Link from 'next/link'
import { useTranslation } from "next-i18next";

export default function Apps({isBreakpoint,page1,topA,toggleTheme,stories}) {
    const { t } = useTranslation("translation");
    const [apis,setApis] = useState([
        {
            id:1,
            name: t("app"),
            desc: t("app.tts.desc"),
            keyword : ["IBM WATSON","TEXT TO SPEECH"],
            url:"/apps/text-to-speech-ibm-wattson"
        }
    ])

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.head}>
                <Header isBreakpoint={isBreakpoint} border={false}/>
            </div>
            <main className={styles.main}>
                <input className={styles.search} type={"search"} placeholder="Search ..."/>
                <div className={styles.apis}>
                    {apis.map((a,i)=>{
                        return(
                            <Link key={i}  href={a?.url}  className={styles.api}>
                                <div >
                                    <div className={styles.top}>
                                        <Image
                                            src={"https://picsum.photos/100/100"}
                                            width={70}
                                            height={70}
                                            alt={a?.name}
                                        />
                                        <span>
                                            {t("app")}
                                        </span>
                                    </div>
                                    <div className={styles.desc}>{a?.desc}</div>
                                    <div className={styles.keywords}>
                                        {a?.keyword?.map((k,i)=>{
                                            return(
                                                <div className={styles.word} key={i}>{k}</div>
                                            )
                                        })}
                                    </div>
                                </div>
                            </Link>
                        )
                    })}
                </div>
            </main>
            <Footer toggleTheme={toggleTheme}/>
        </div>
    )
}
