import React from 'react'
import Head from 'next/head'
import Header from '../components/Header'
import styles from './index.module.scss'
import Footer from '../components/Footer'

export default function About({isBreakpoint}) {
  return (
    <div className={styles.container}>
        <Head>
            <title>LSB || About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header isBreakpoint={isBreakpoint}/>
        <main className={styles.main}>
            <h1>A propos</h1>
        </main>
        <Footer/>

    </div>
  )
}
