import React from 'react'
import Head from 'next/head'
import Header from '../components/Header'
import styles from './index.module.scss'
import Logo from '../components/Logo'
import Footer from '../components/Footer'

export default function Contact({isBreakpoint}) {
  return (
    <div className={styles.container}>
        <Head>
            <title>LSB || Contact nous</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <script async src="https://www.googletagmanager.com/gtag/js?id=G-WV85CLJKTF"></script>

        </Head>
        <Header isBreakpoint={isBreakpoint}/>
        <main className={styles.main}>
            <script dangerouslySetInnerHTML={{__html:`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-WV85CLJKTF');
            `}}/>
            <h1 style={{marginTop:"1rem"}}>Contactez nous</h1>
            <p>Nous sommes à votre écoute</p>
            <div className={styles.contact}>
                <div>
                    <h3 style={{display:"flex",alignItems:"center"}}>Service client <Logo style={{marginLeft:"1rem"}}/></h3>
                    <p>Vous avez une recommendation pour ou nous ou une requête à nous soumettre ? N'hésitez pas notre service client étudiera votre message avec soin et attention.
                        <br></br>Merci à vous !!!</p>
                    <a href='mailto:contact@w4coder.com'>Email : contact@w4coder.com</a>
                </div>
                <form className={styles.contactForm}>
                    <input type={"text"} name="name" placeholder="Full Name"/>
                    <input type={"email"} name="Email" placeholder="Email"/>
                    <textarea 
                        placeholder="Your message"
                        rows={6}
                    >

                    </textarea>
                    <input type={"submit"} value={"Submit"}/>
                </form>
            </div>
        </main>
        <Footer/>

    </div>
  )
}
