import Head from 'next/head'
import Image from 'next/image'
import styles from './index.module.scss'
import HomePage from '../components/HomePage'
import { getTopArticles,getArticle } from '../services/articles'
import {getStories} from '../services/stories'
import Header from '../components/Header'
import Footer from '../components/Footer'
import { useRouter } from 'next/router'


export default function Home({isBreakpoint,page1,topA,toggleTheme,stories}) {

  const router = useRouter()
  const lang = router.locale

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isBreakpoint={isBreakpoint} />
      <main className={styles.main}>
        <HomePage isBreakpoint={isBreakpoint} topA={topA} page1={page1} stories={stories} lang={lang}/>      
      </main>
      <Footer toggleTheme={toggleTheme}/>
      
    </div>
  )
}

export async function getServerSideProps({locale}) {
  // Fetch data from external API

  const page1 =  await getArticle({filter:{
    page : 1,
    lang : locale
  }})

  const stories =  await getStories({filter:{
    page : 1,
    lang : locale
  }})
  //console.log(res.length)

  return { 
      props: {
        page1 : page1 || [],
        stories : stories || [],
        topA :  []
      } 
  }
}