import Head from 'next/head'
import Image from 'next/image'
import styles from './index.module.scss'
import Header from '../components/Header'
import HomePage from '../components/HomePage'
import { getTopArticles,getArticle } from '../services/articles'
import Footer from '../components/Footer'

export default function Home({isBreakpoint,page1,topA,toggleTheme}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isBreakpoint={isBreakpoint}/>
      <main className={styles.main}>
        <HomePage isBreakpoint={isBreakpoint} topA={topA} page1={page1}/>      
      </main>
      <Footer toggleTheme={toggleTheme}/>
      
    </div>
  )
}

export async function getServerSideProps(context) {
  // Fetch data from external API

  const page1 =  await getArticle({filter:{
    page : 1
  }})


  //console.log(res.length)

  return { 
      props: {
        page1 : page1 || [],
        topA :  []
      } 
  }
}