import React, { useState } from 'react'
import Head from 'next/head'
import Header from '../components/Header'
import styles from './index.module.scss'
import Footer from '../components/Footer'

export default function Newsletter({isBreakpoint}) {

    const [email,setEmail] = useState(false)

    return (
        <div className={styles.container}>
            <Head>
                <title>LSB || News Letter</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header isBreakpoint={isBreakpoint}/>
            <main className={styles.main}>
                <h1 style={{textAlign:"center"}}>Inscrivez-vous à notre newsletter.</h1>
                <br></br>
                <p style={{lineHeight:"1.5",textAlign:"center",margin:"1rem"}}>Ne manquez aucun de nos article, story ou tutoriel avec notre newsletter hebdomadaire.</p>
                <form className={styles.newLetterForm}>
                    <input type={"email"} placeholder={"Email"} onChange={(e)=>{setEmail(e.target.value)}}/>
                    <input type={"submit"} value="S'inscrire"/>
                </form>
            </main>
            <Footer/>

        </div>
    )
}
