import React from 'react'
import Head from 'next/head'
import Header from '../components/Header'
import styles from './index.module.scss'
import Footer from '../components/Footer'
import { getStories } from '../services/stories'
import Image from 'next/image'
import Link from 'next/link'

export default function Youtube({isBreakpoint,stories}) {
  return (
    <div className={styles.container}>
        <Head>
            <title>LSB || YouTube</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header isBreakpoint={isBreakpoint}/>
        <main className={styles.main}>
            {/* <h1 style={{marginTop:"1rem"}}>Web Stories</h1> */}
           
            <div className={styles.youtube}>

                <div style={{display:"flex",alignItems:"center"}}>
                    <svg viewBox="0 0 40 24" preserveAspectRatio="xMidYMid meet" focusable="false" style={{pointerEvents: "none", display: "block", height: "20px"}} class="style-scope yt-icon">
                        <g viewBox="0 0 20 20" preserveAspectRatio="xMidYMid meet" class="style-scope yt-icon">
                            <g class="style-scope yt-icon">
                                <path d="M27.9727 3.12324C27.6435 1.89323 26.6768 0.926623 25.4468 0.597366C23.2197 2.24288e-07 14.285 0 14.285 0C14.285 0 5.35042 2.24288e-07 3.12323 0.597366C1.89323 0.926623 0.926623 1.89323 0.597366 3.12324C2.24288e-07 5.35042 0 10 0 10C0 10 2.24288e-07 14.6496 0.597366 16.8768C0.926623 18.1068 1.89323 19.0734 3.12323 19.4026C5.35042 20 14.285 20 14.285 20C14.285 20 23.2197 20 25.4468 19.4026C26.6768 19.0734 27.6435 18.1068 27.9727 16.8768C28.5701 14.6496 28.5701 10 28.5701 10C28.5701 10 28.5677 5.35042 27.9727 3.12324Z" fill="#FF0000" class="style-scope yt-icon"></path>
                                <path d="M11.4253 14.2854L18.8477 10.0004L11.4253 5.71533V14.2854Z" fill="white" class="style-scope yt-icon"></path>
                            </g>
                        </g>
                    </svg>
                    <span style={{
                        fontSize: "1.1rem",
                        lineHeight: "2.8rem",
                        fontWeight: 400,
                    }}>YouTube</span>
                </div>
                <br></br>
                <div className={styles.list}>

                </div>
                <div style={{display:"flex",alignItems:"center"}}>
                    <svg viewBox="0 0 40 " preserveAspectRatio="xMidYMid meet" focusable="false" style={{pointerEvents: "none", display: "block", width: "34px", height: "24px"}} class="style-scope yt-icon"><g width="24" height="24" viewBox="0 0 24 24" class="style-scope yt-icon"><g class="style-scope yt-icon"><path d="M17.77,10.32l-1.2-.5L18,9.06a3.74,3.74,0,0,0-3.5-6.62L6,6.94a3.74,3.74,0,0,0,.23,6.74l1.2.49L6,14.93a3.75,3.75,0,0,0,3.5,6.63l8.5-4.5a3.74,3.74,0,0,0-.23-6.74Z" fill="red" class="style-scope yt-icon"></path><polygon points="10 14.65 15 12 10 9.35 10 14.65" fill="#fff" class="style-scope yt-icon"></polygon></g></g></svg>
                    <span style={{
                        fontSize: "1.1rem",
                        lineHeight: "2.8rem",
                        fontWeight: 400,
                    }}>Shorts</span>
                </div>
                <div className={styles.list}>

                </div>
            </div>
            <div>
                
            </div>
        </main>
        <Footer/>

    </div>
  )
}

export async function getServerSideProps(context) {
    // Fetch data from external API
  
    const stories =  await getStories({filter:{
        page : 1
    }})
  
    //console.log(res.length)
  
    return { 
        props: {
            stories : stories || [],
        } 
    }
  }
